"""
Module 5 – Metadata Analysis
Extracts and forensically evaluates document metadata for PPTX and PDF files.
Flags suspicious authorship signals, timestamp anomalies, and generator tool
inconsistencies that indicate programmatic or fraudulent document creation.
"""

import zipfile
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

from pptx import Presentation
import fitz  # PyMuPDF

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Known programmatic / generator tool strings that indicate machine-generated docs
PROGRAMMATIC_TOOL_SIGNATURES: list[str] = [
    "pptxgenjs",
    "python-pptx",
    "libreoffice",
    "openoffice",
    "aspose",
    "spire",
    "googleslides",
    "google slides",
    "wps office",
    "keynote",
    "canva",
    "slidesgo",
    "templateswise",
    "slidescarnival",
    "chatgpt",
    "gemini",
    "copilot",
    "auto-generated",
    "autogenerated",
    "script",
    "bot",
    "tool",
]

# Known legitimate authoring applications (used in Flag 4 cross-check)
LEGITIMATE_APPLICATIONS: list[str] = [
    "microsoft office",
    "microsoft powerpoint",
    "microsoft word",
    "microsoft excel",
    "powerpoint",
    "word",
    "excel",
]

# XML namespace map used in OOXML core/app properties
_NS = {
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcterms": "http://purl.org/dc/terms/",
    "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    "vt": "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes",
    "": "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties",
}

_APP_NS = "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"


# ---------------------------------------------------------------------------
# PPTX helpers
# ---------------------------------------------------------------------------

def _parse_iso_datetime(value: str | None) -> datetime | None:
    """Parse an ISO-8601 datetime string to an aware datetime object."""
    if not value:
        return None
    value = value.strip().rstrip("Z")
    try:
        dt = datetime.fromisoformat(value)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except ValueError:
        return None


def _fmt_dt(dt: datetime | None) -> str | None:
    """Format a datetime to ISO-8601 string or return None."""
    if dt is None:
        return None
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _xml_text(element: ET.Element | None, tag: str, ns: str = "") -> str | None:
    """Safely extract text from an XML element by tag."""
    if element is None:
        return None
    if ns:
        child = element.find(f"{{{ns}}}{tag}")
    else:
        child = element.find(tag)
    return child.text.strip() if child is not None and child.text else None


def _read_pptx_xml(file_path: Path) -> tuple[ET.Element | None, ET.Element | None]:
    """
    Open the PPTX (ZIP) and parse docProps/core.xml and docProps/app.xml.
    Returns (core_root, app_root).  Either may be None if the part is absent.
    """
    core_root: ET.Element | None = None
    app_root: ET.Element | None = None

    try:
        with zipfile.ZipFile(str(file_path), "r") as zf:
            names = zf.namelist()
            if "docProps/core.xml" in names:
                with zf.open("docProps/core.xml") as f:
                    core_root = ET.fromstring(f.read())
            if "docProps/app.xml" in names:
                with zf.open("docProps/app.xml") as f:
                    app_root = ET.fromstring(f.read())
    except (zipfile.BadZipFile, ET.ParseError):
        pass

    return core_root, app_root


def _extract_pptx_metadata(file_path: Path) -> dict:
    """
    Combine python-pptx core properties with raw XML parsing of
    docProps/core.xml and docProps/app.xml for full metadata coverage.
    """
    prs = Presentation(str(file_path))
    props = prs.core_properties
    core_root, app_root = _read_pptx_xml(file_path)

    # --- Core properties via python-pptx (convenient typed access) ---
    creator: str | None = props.author or None
    last_modified_by: str | None = props.last_modified_by or None
    created_dt: datetime | None = props.created
    modified_dt: datetime | None = props.modified
    revision: int | None = props.revision
    title: str | None = props.title or None
    subject: str | None = props.subject or None
    keywords: str | None = props.keywords or None

    # Normalise to aware datetimes
    if created_dt and created_dt.tzinfo is None:
        created_dt = created_dt.replace(tzinfo=timezone.utc)
    if modified_dt and modified_dt.tzinfo is None:
        modified_dt = modified_dt.replace(tzinfo=timezone.utc)

    # --- App properties via raw XML (python-pptx doesn't expose all of these) ---
    application: str | None = None
    app_version: str | None = None
    company: str | None = None
    total_time: int | None = None

    if app_root is not None:
        application = _xml_text(app_root, "Application", _APP_NS)
        app_version = _xml_text(app_root, "AppVersion", _APP_NS)
        company = _xml_text(app_root, "Company", _APP_NS)
        raw_total_time = _xml_text(app_root, "TotalTime", _APP_NS)
        if raw_total_time is not None:
            try:
                total_time = int(raw_total_time)
            except ValueError:
                total_time = None

    return {
        "creator": creator,
        "last_modified_by": last_modified_by,
        "created_dt": created_dt,
        "modified_dt": modified_dt,
        "revision": revision,
        "title": title,
        "subject": subject,
        "keywords": keywords,
        "application": application,
        "app_version": app_version,
        "company": company,
        "total_time_minutes": total_time,
    }


# ---------------------------------------------------------------------------
# PDF helpers
# ---------------------------------------------------------------------------

def _extract_pdf_metadata(file_path: Path) -> dict:
    """
    Extract metadata from a PDF using PyMuPDF.
    Reads both the classic /Info dictionary and the XMP metadata packet.
    """
    creator: str | None = None
    last_modified_by: str | None = None
    created_dt: datetime | None = None
    modified_dt: datetime | None = None
    application: str | None = None
    app_version: str | None = None
    title: str | None = None
    subject: str | None = None
    keywords: str | None = None
    producer: str | None = None

    with fitz.open(str(file_path)) as doc:
        info: dict = doc.metadata or {}

        creator = info.get("author") or None
        title = info.get("title") or None
        subject = info.get("subject") or None
        keywords = info.get("keywords") or None
        application = info.get("creator") or None  # /Creator = authoring app
        producer = info.get("producer") or None      # /Producer = PDF library

        # PyMuPDF returns dates as "D:YYYYMMDDHHmmSSOHH'mm'" strings
        raw_created = info.get("creationDate", "")
        raw_modified = info.get("modDate", "")
        created_dt = _parse_pdf_date(raw_created)
        modified_dt = _parse_pdf_date(raw_modified)

        # XMP packet for richer metadata
        xmp_xml: str | None = doc.get_xml_metadata()
        if xmp_xml:
            xmp_data = _parse_xmp(xmp_xml)
            # XMP fields override /Info where present
            creator = xmp_data.get("creator") or creator
            last_modified_by = xmp_data.get("modifier") or last_modified_by
            app_version = xmp_data.get("app_version") or app_version
            created_dt = xmp_data.get("created_dt") or created_dt
            modified_dt = xmp_data.get("modified_dt") or modified_dt

    return {
        "creator": creator,
        "last_modified_by": last_modified_by,
        "created_dt": created_dt,
        "modified_dt": modified_dt,
        "revision": None,
        "title": title,
        "subject": subject,
        "keywords": keywords,
        "application": application,
        "app_version": app_version,
        "company": None,
        "total_time_minutes": None,
        "producer": producer,
    }


def _parse_pdf_date(raw: str) -> datetime | None:
    """
    Parse a PDF date string of the form "D:YYYYMMDDHHmmSSOHH'mm'".
    Falls back to ISO parsing for non-standard strings.
    """
    if not raw:
        return None
    raw = raw.strip()
    if raw.startswith("D:"):
        raw = raw[2:]
    # Strip timezone portion for simple parsing
    raw_core = raw[:14]
    try:
        return datetime.strptime(raw_core, "%Y%m%d%H%M%S").replace(tzinfo=timezone.utc)
    except ValueError:
        pass
    # Fallback for ISO-like strings
    return _parse_iso_datetime(raw)


def _parse_xmp(xmp_xml: str) -> dict:
    """
    Parse an XMP metadata XML string and extract key authorship fields.
    Returns a dict with keys: creator, modifier, created_dt, modified_dt, app_version.
    """
    result: dict = {}
    try:
        root = ET.fromstring(xmp_xml)
    except ET.ParseError:
        return result

    # Walk all elements; collect text by local tag name
    for elem in root.iter():
        local = elem.tag.split("}")[-1] if "}" in elem.tag else elem.tag
        text = (elem.text or "").strip()
        if not text:
            continue

        lower_local = local.lower()
        if lower_local in ("creator", "author") and "creator" not in result:
            result["creator"] = text
        elif lower_local in ("modifiedby", "modifier") and "modifier" not in result:
            result["modifier"] = text
        elif lower_local == "createdate" and "created_dt" not in result:
            result["created_dt"] = _parse_iso_datetime(text)
        elif lower_local == "modifydate" and "modified_dt" not in result:
            result["modified_dt"] = _parse_iso_datetime(text)
        elif lower_local in ("creatortool", "appversion") and "app_version" not in result:
            result["app_version"] = text

    return result


# ---------------------------------------------------------------------------
# Flag detection logic
# ---------------------------------------------------------------------------

def _contains_generator_signature(value: str | None) -> tuple[bool, str | None]:
    """
    Return (True, matched_signature) if *value* contains any known programmatic
    tool name, case-insensitively.
    """
    if not value:
        return False, None
    lower = value.lower()
    for sig in PROGRAMMATIC_TOOL_SIGNATURES:
        if sig in lower:
            return True, sig
    return False, None


def _detect_flags(meta: dict, file_type: str) -> list[dict]:
    """
    Evaluate the four forensic flags defined for PPTX, with PDF-compatible
    subset where applicable.
    """
    flags: list[dict] = []
    ft = file_type.lower().lstrip(".")

    subject: str | None = meta.get("subject")
    company: str | None = meta.get("company")
    application: str | None = meta.get("application")
    total_time: int | None = meta.get("total_time_minutes")
    created_dt: datetime | None = meta.get("created_dt")
    modified_dt: datetime | None = meta.get("modified_dt")
    creator: str | None = meta.get("creator")
    producer: str | None = meta.get("producer")  # PDF-only

    # -- Flag 1: Generator tool signature in subject / company / producer --------
    for field_name, field_value in [
        ("subject", subject),
        ("company", company),
        ("application", application),
        ("creator/application", creator),
        ("producer", producer),
    ]:
        hit, sig = _contains_generator_signature(field_value)
        if hit:
            flags.append({
                "flag_id": "FLAG_01",
                "description": (
                    f"Programmatic generator tool detected in '{field_name}' field: "
                    f"'{field_value}' (matched signature: '{sig}')"
                ),
                "severity": "High",
            })
            break  # One Flag 1 is sufficient

    # -- Flag 2: Created == Modified (identical timestamps) ----------------------
    if created_dt is not None and modified_dt is not None:
        # Compare at second-level precision
        if created_dt.replace(microsecond=0) == modified_dt.replace(microsecond=0):
            flags.append({
                "flag_id": "FLAG_02",
                "description": (
                    "Created and modified timestamps are identical "
                    f"({_fmt_dt(created_dt)}), suggesting no real editing occurred."
                ),
                "severity": "Medium",
            })

    # -- Flag 3: TotalTime == 0 (PPTX-only) -------------------------------------
    if ft == "pptx" and total_time is not None and total_time == 0:
        flags.append({
            "flag_id": "FLAG_03",
            "description": (
                "Total editing time (TotalTime) is 0 minutes, indicating the file "
                "was never interactively edited in PowerPoint."
            ),
            "severity": "High",
        })

    # -- Flag 4: Application field inconsistent with detected generator ----------
    #    If Flag 1 fired (generator found) AND the Application claims to be
    #    a legitimate Microsoft app, the two are contradictory.
    flag_1_fired = any(f["flag_id"] == "FLAG_01" for f in flags)
    if flag_1_fired and application:
        app_lower = application.lower()
        claims_legitimate = any(leg in app_lower for leg in LEGITIMATE_APPLICATIONS)
        if claims_legitimate:
            flags.append({
                "flag_id": "FLAG_04",
                "description": (
                    f"Application field claims '{application}' (a legitimate editor), "
                    "but a programmatic generator signature was detected elsewhere. "
                    "This inconsistency suggests the metadata was spoofed."
                ),
                "severity": "High",
            })

    return flags


# ---------------------------------------------------------------------------
# Integrity & confidence scoring
# ---------------------------------------------------------------------------

_SEVERITY_WEIGHT: dict[str, float] = {
    "High": 0.30,
    "Medium": 0.15,
    "Low": 0.05,
}


def _compute_integrity_and_confidence(flags: list[dict]) -> tuple[str, float]:
    """
    Derive a metadata_integrity label and a confidence score from the active flags.

    Integrity scale:
      High   → no flags (document looks authentic)
      Medium → only Medium/Low severity flags
      Low    → at least one High-severity flag
    """
    if not flags:
        return "High", 1.0

    high_count = sum(1 for f in flags if f["severity"] == "High")
    medium_count = sum(1 for f in flags if f["severity"] == "Medium")

    total_penalty = sum(_SEVERITY_WEIGHT.get(f["severity"], 0.0) for f in flags)
    confidence = round(max(0.0, 1.0 - total_penalty), 2)

    if high_count > 0:
        integrity = "Low"
    elif medium_count > 0:
        integrity = "Medium"
    else:
        integrity = "High"

    return integrity, confidence


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def analyze_metadata(file_path: str, file_type: str) -> dict:
    """
    Analyse document metadata and return a structured forensic report.

    Args:
        file_path: Absolute or relative path to the document on disk.
        file_type: File extension without dot (pptx, pdf).

    Returns:
        {
            creator, last_modified_by, created_timestamp, modified_timestamp,
            revision_count, app_version, generator_tool,
            total_editing_time_minutes,
            flags: [ { flag_id, description, severity } ],
            metadata_integrity: "Low" | "Medium" | "High",
            confidence: float,
        }

    Raises:
        FileNotFoundError: If the document does not exist on disk.
        ValueError: If the file_type is unsupported.
    """
    path = Path(file_path)
    if not path.is_file():
        raise FileNotFoundError(f"Document not found: {file_path}")

    normalized_type = file_type.lower().lstrip(".")

    if normalized_type == "pptx":
        meta = _extract_pptx_metadata(path)
    elif normalized_type == "pdf":
        meta = _extract_pdf_metadata(path)
    else:
        raise ValueError(f"Unsupported file type for metadata analysis: {file_type}")

    flags = _detect_flags(meta, normalized_type)
    integrity, confidence = _compute_integrity_and_confidence(flags)

    # Determine generator_tool: the first programmatic signature found in any field
    generator_tool: str | None = None
    for field in ("application", "subject", "company", "creator"):
        hit, sig = _contains_generator_signature(meta.get(field))
        if hit:
            generator_tool = sig
            break
    # PDF: also check producer
    if generator_tool is None:
        hit, sig = _contains_generator_signature(meta.get("producer"))
        if hit:
            generator_tool = sig

    return {
        "creator": meta.get("creator"),
        "last_modified_by": meta.get("last_modified_by"),
        "created_timestamp": _fmt_dt(meta.get("created_dt")),
        "modified_timestamp": _fmt_dt(meta.get("modified_dt")),
        "revision_count": meta.get("revision"),
        "app_version": meta.get("app_version"),
        "generator_tool": generator_tool,
        "total_editing_time_minutes": meta.get("total_time_minutes"),
        "flags": flags,
        "metadata_integrity": integrity,
        "confidence": confidence,
    }
